class HTTPStatusCode {
    OK = 200; //success
    BAD_REQUEST = 400;
    NOT_FOUND = 404;
    INTERNAL_SERVER =  500;
    UNAUTHORIZED = 401;
    CREATED =201; // create
}
class ErrorMessages {
    USER_REGISTER_SUCCESS = "User Registred Successfully";
    LOGIN_SUCCESS = "Login Successfully";
    LOGIN_FIRST = "Please Login First";
    INVALID_TOKEN = "Invalid Token";
    UPLOAD_SUCCESS = "File Uploaded Successfully";
    PASSWORD_DOES_NOT_MATCH= "Password does not match.";
    PASSWORD_UPDATED= "Password successfully updated.";
    USER_REGISTER_FAILED = "User Registration Failed";
    USER_EXIST = "User already exists";
    EMAIL_EXIST = "Email already exists";
    EMAIL_DOES_NOT_EXIST = "Email does not exists";
    INVALID_EMAIL = "Invalid Email ID";
    COUNTRY_EXIST = "Country already exists";
    STATE_EXIST = "Country already exists";
    CITY_EXIST = "City already exists";
    COURSE_EXIST = "Course already you created.";
    CONTENT_EXIST = "Content already exists";
    CONTENT_VIDEO_EXIST = "Content Video already exists";
    MOBILE_NO_EXIST = "Mobile Number already exists";
    CATEGORY_EXIST = "Category already exists";
    SUBCATEGORY_EXIST = "Subcategory already exists";
    PROGRAMMING_LANGUAGE_EXIST = "Programming Language already exists";
    LANGUAGE_EXIST = "Language already exists";
    VIDEO_EXIST = "Video already exists";
    CHAPTER_EXIST = "Chapter already exists";
    INVALID_CHAPTER = "Chapter is from another Course";
    WRONG_CREDENTIALS = "Invalid Credentials";
    SUCCESS = "Login Successfully";
    OTP_SENT = "OTP send to your email successfully";
    NOT_EXISTS = "Data does not exists";
    SAVED = "Saved Successfully";
    CREATED = "Created Successfully";
    GETDATA = "Got data Successfully";
    UPDATED = "Updated Successfully";
    DELETED = "Deleted Successfully";
    NOT_FOUND = "Record not found";
    REVIEW_NOT = "There is no review about this course"
    INTERNAL_SERVER = 'Server error!';
    ADDED = "Record Added Successfully";
    VIDEO_UPLOAD = "Video Uploaded Successfully";
    INVALID_OBJECT_ID = "Invalid Objectid";
    COURSE_NOT_FOUND = "Course does not exists";
    INSTRUCTOR_NOT_EXIST = "Instructor does not exists";
    CATEGORY_NOT_FOUND = "Category does not exists";
    SUBCATEGORY_NOT_FOUND = "Subcategory does not exists";
    LANGUAGE_NOT_FOUND = "Language does not exists";
    FILE_NOT_FOUND = "File does not exists";
    VIDEO_NOT_FOUND = "Video does not exists";
    REVIEW_ADD = "Review added Successfully";
    INVALID = "Invalid Credentialsssss"
    PAYMENT_VARFIED_SUCCESS = "Payment Varifies Successfully"
    PAYMENT_VARFIED_FAIL = "Payment Varifies Fail"
    MYCOURSE_SUCCESS = "Course added to mycourse successfully."
    MYCOURSE_FAIL = "Course is fail to added to my course."
}
module.exports.HTTPStatusCode = new HTTPStatusCode()
module.exports.ErrorMessages = new  ErrorMessages()